### PR TITLE
Avoid having LTI Consumer XBlock references

### LINKED ISSUE #6: Stale README
The README is copied from the LTI Consumer XBlock without modifications. This is confusing.

### PR DESCRIPTION
**Pull request by OmarIthawi**
Start with a clean README.

Close #6

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @OmarIthawi! I've created [OSPR-4035](https://openedx.atlassian.net/browse/OSPR-4035) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).

**Comment by natabene** [comment]
@OmarIthawi Thank you for your contribution, is this ready for our review?

**Comment by OmarIthawi** [comment]
Yes @natabene it is ready for review. It's not perfect but better than what we have.

I suppose it still could have some more content. But honestly I don't know what the `zoom-xblock` is to write a proper description but I know for sure that this is not the LTI Consumer XBlock, therefore the README emptying.

**Comment by natabene** [comment]
@OmarIthawi Got it. @nedbat  Can you review this please?

**Comment by edx-webhook** [comment]
@OmarIthawi 🎉 Your pull request was merged!

Please take a moment to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=edx/edx-zoom&entry.867055334=https://github.com/edx/edx-zoom/pull/7&entry.1484655318=https://github.com/OmarIthawi&entry.752974735=2020-01-13+15:43&entry.1917517419=2020-01-13+21:36&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
